project_id = "mjkjygzxwysbhgjtvobm"

[functions.wayforpay-callback]
verify_jwt = false

[functions.telegram-notify-registration]
verify_jwt = false

[functions.telegram-notify-signup]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
