/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as MapRouteImport } from './routes/map'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PublicOfferRouteImport } from './routes/public-offer'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as UserAgreementRouteImport } from './routes/user-agreement'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCampaignsRouteImport } from './routes/admin/campaigns'
import { Route as AdminCarouselRouteImport } from './routes/admin/carousel'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminStartsRouteImport } from './routes/admin/starts'
import { Route as AdminSurveyRouteImport } from './routes/admin/survey'
import { Route as AdminUnsubscribesRouteImport } from './routes/admin/unsubscribes'
import { Route as CategoryIndexRouteImport } from './routes/category/index'
import { Route as CategoryCategoryRouteImport } from './routes/category/$category'
import { Route as ClubsIndexRouteImport } from './routes/clubs/index'
import { Route as ClubsSlugRouteImport } from './routes/clubs/$slug'
import { Route as ClubsEditRouteImport } from './routes/clubs/edit'
import { Route as EventIdRouteImport } from './routes/event/$id'
import { Route as OrganizerIndexRouteImport } from './routes/organizer/index'
import { Route as OrganizersIndexRouteImport } from './routes/organizers/index'
import { Route as OrganizersSlugRouteImport } from './routes/organizers/$slug'
import { Route as OrganizersEditRouteImport } from './routes/organizers/edit'
import { Route as PaymentFailIndexRouteImport } from './routes/payment-fail/index'
import { Route as PaymentSuccessIndexRouteImport } from './routes/payment-success/index'
import { Route as PaymentFailRouteImport } from './routes/payment/fail'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as StartsIndexRouteImport } from './routes/starts/index'
import { Route as StartsSlugRouteImport } from './routes/starts/$slug'
import { Route as StravaCallbackRouteImport } from './routes/strava/callback'
import { Route as TicketIdRouteImport } from './routes/ticket/$id'
import { Route as EventsIdIndexRouteImport } from './routes/events/$id/index'
import { Route as EventsIdParticipantsRouteImport } from './routes/events/$id/participants'
import { Route as EventsIdResultsRouteImport } from './routes/events/$id/results'
import { Route as OrganizerEventsNewRouteImport } from './routes/organizer/events/new'
import { Route as AdminEventsIdCoOrganizersRouteImport } from './routes/admin/events/$id/co-organizers'
import { Route as OrganizerEventsIdIndexRouteImport } from './routes/organizer/events/$id/index'
import { Route as OrganizerEventsIdAnalyticsRouteImport } from './routes/organizer/events/$id/analytics'
import { Route as OrganizerEventsIdCampaignRouteImport } from './routes/organizer/events/$id/campaign'
import { Route as OrganizerEventsIdChangesRouteImport } from './routes/organizer/events/$id/changes'
import { Route as OrganizerEventsIdPromoCodesRouteImport } from './routes/organizer/events/$id/promo-codes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicOfferRoute = PublicOfferRouteImport.update({
  id: '/public-offer',
  path: '/public-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAgreementRoute = UserAgreementRouteImport.update({
  id: '/user-agreement',
  path: '/user-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/admin/campaigns',
  path: '/admin/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCarouselRoute = AdminCarouselRouteImport.update({
  id: '/admin/carousel',
  path: '/admin/carousel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/admin/sessions',
  path: '/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStartsRoute = AdminStartsRouteImport.update({
  id: '/admin/starts',
  path: '/admin/starts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSurveyRoute = AdminSurveyRouteImport.update({
  id: '/admin/survey',
  path: '/admin/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnsubscribesRoute = AdminUnsubscribesRouteImport.update({
  id: '/admin/unsubscribes',
  path: '/admin/unsubscribes',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsSlugRoute = ClubsSlugRouteImport.update({
  id: '/clubs/$slug',
  path: '/clubs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsEditRoute = ClubsEditRouteImport.update({
  id: '/clubs/edit',
  path: '/clubs/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/organizer/',
  path: '/organizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersIndexRoute = OrganizersIndexRouteImport.update({
  id: '/organizers/',
  path: '/organizers/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersSlugRoute = OrganizersSlugRouteImport.update({
  id: '/organizers/$slug',
  path: '/organizers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersEditRoute = OrganizersEditRouteImport.update({
  id: '/organizers/edit',
  path: '/organizers/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailIndexRoute = PaymentFailIndexRouteImport.update({
  id: '/payment-fail/',
  path: '/payment-fail/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessIndexRoute = PaymentSuccessIndexRouteImport.update({
  id: '/payment-success/',
  path: '/payment-success/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailRoute = PaymentFailRouteImport.update({
  id: '/payment/fail',
  path: '/payment/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const StartsIndexRoute = StartsIndexRouteImport.update({
  id: '/starts/',
  path: '/starts/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartsSlugRoute = StartsSlugRouteImport.update({
  id: '/starts/$slug',
  path: '/starts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StravaCallbackRoute = StravaCallbackRouteImport.update({
  id: '/strava/callback',
  path: '/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIdRoute = TicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdIndexRoute = EventsIdIndexRouteImport.update({
  id: '/events/$id/',
  path: '/events/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdParticipantsRoute = EventsIdParticipantsRouteImport.update({
  id: '/events/$id/participants',
  path: '/events/$id/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdResultsRoute = EventsIdResultsRouteImport.update({
  id: '/events/$id/results',
  path: '/events/$id/results',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventsNewRoute = OrganizerEventsNewRouteImport.update({
  id: '/organizer/events/new',
  path: '/organizer/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIdCoOrganizersRoute =
  AdminEventsIdCoOrganizersRouteImport.update({
    id: '/admin/events/$id/co-organizers',
    path: '/admin/events/$id/co-organizers',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerEventsIdIndexRoute = OrganizerEventsIdIndexRouteImport.update({
  id: '/organizer/events/$id/',
  path: '/organizer/events/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventsIdAnalyticsRoute =
  OrganizerEventsIdAnalyticsRouteImport.update({
    id: '/organizer/events/$id/analytics',
    path: '/organizer/events/$id/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerEventsIdCampaignRoute =
  OrganizerEventsIdCampaignRouteImport.update({
    id: '/organizer/events/$id/campaign',
    path: '/organizer/events/$id/campaign',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerEventsIdChangesRoute =
  OrganizerEventsIdChangesRouteImport.update({
    id: '/organizer/events/$id/changes',
    path: '/organizer/events/$id/changes',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerEventsIdPromoCodesRoute =
  OrganizerEventsIdPromoCodesRouteImport.update({
    id: '/organizer/events/$id/promo-codes',
    path: '/organizer/events/$id/promo-codes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/contacts': typeof ContactsRoute
  '/features': typeof FeaturesRoute
  '/map': typeof MapRoute
  '/my-events': typeof MyEventsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/public-offer': typeof PublicOfferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/survey': typeof SurveyRoute
  '/testimonials': typeof TestimonialsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/user-agreement': typeof UserAgreementRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/carousel': typeof AdminCarouselRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/starts': typeof AdminStartsRoute
  '/admin/survey': typeof AdminSurveyRoute
  '/admin/unsubscribes': typeof AdminUnsubscribesRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/clubs/edit': typeof ClubsEditRoute
  '/event/$id': typeof EventIdRoute
  '/organizers/$slug': typeof OrganizersSlugRoute
  '/organizers/edit': typeof OrganizersEditRoute
  '/payment/fail': typeof PaymentFailRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/starts/$slug': typeof StartsSlugRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/ticket/$id': typeof TicketIdRoute
  '/admin/': typeof AdminIndexRoute
  '/category/': typeof CategoryIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/organizers/': typeof OrganizersIndexRoute
  '/payment-fail/': typeof PaymentFailIndexRoute
  '/payment-success/': typeof PaymentSuccessIndexRoute
  '/starts/': typeof StartsIndexRoute
  '/events/$id/participants': typeof EventsIdParticipantsRoute
  '/events/$id/results': typeof EventsIdResultsRoute
  '/organizer/events/new': typeof OrganizerEventsNewRoute
  '/events/$id/': typeof EventsIdIndexRoute
  '/admin/events/$id/co-organizers': typeof AdminEventsIdCoOrganizersRoute
  '/organizer/events/$id/analytics': typeof OrganizerEventsIdAnalyticsRoute
  '/organizer/events/$id/campaign': typeof OrganizerEventsIdCampaignRoute
  '/organizer/events/$id/changes': typeof OrganizerEventsIdChangesRoute
  '/organizer/events/$id/promo-codes': typeof OrganizerEventsIdPromoCodesRoute
  '/organizer/events/$id/': typeof OrganizerEventsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/contacts': typeof ContactsRoute
  '/features': typeof FeaturesRoute
  '/map': typeof MapRoute
  '/my-events': typeof MyEventsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/public-offer': typeof PublicOfferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/survey': typeof SurveyRoute
  '/testimonials': typeof TestimonialsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/user-agreement': typeof UserAgreementRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/carousel': typeof AdminCarouselRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/starts': typeof AdminStartsRoute
  '/admin/survey': typeof AdminSurveyRoute
  '/admin/unsubscribes': typeof AdminUnsubscribesRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/clubs/edit': typeof ClubsEditRoute
  '/event/$id': typeof EventIdRoute
  '/organizers/$slug': typeof OrganizersSlugRoute
  '/organizers/edit': typeof OrganizersEditRoute
  '/payment/fail': typeof PaymentFailRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/starts/$slug': typeof StartsSlugRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/ticket/$id': typeof TicketIdRoute
  '/admin': typeof AdminIndexRoute
  '/category': typeof CategoryIndexRoute
  '/clubs': typeof ClubsIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/organizers': typeof OrganizersIndexRoute
  '/payment-fail': typeof PaymentFailIndexRoute
  '/payment-success': typeof PaymentSuccessIndexRoute
  '/starts': typeof StartsIndexRoute
  '/events/$id/participants': typeof EventsIdParticipantsRoute
  '/events/$id/results': typeof EventsIdResultsRoute
  '/organizer/events/new': typeof OrganizerEventsNewRoute
  '/events/$id': typeof EventsIdIndexRoute
  '/admin/events/$id/co-organizers': typeof AdminEventsIdCoOrganizersRoute
  '/organizer/events/$id/analytics': typeof OrganizerEventsIdAnalyticsRoute
  '/organizer/events/$id/campaign': typeof OrganizerEventsIdCampaignRoute
  '/organizer/events/$id/changes': typeof OrganizerEventsIdChangesRoute
  '/organizer/events/$id/promo-codes': typeof OrganizerEventsIdPromoCodesRoute
  '/organizer/events/$id': typeof OrganizerEventsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/contacts': typeof ContactsRoute
  '/features': typeof FeaturesRoute
  '/map': typeof MapRoute
  '/my-events': typeof MyEventsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/public-offer': typeof PublicOfferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/survey': typeof SurveyRoute
  '/testimonials': typeof TestimonialsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/user-agreement': typeof UserAgreementRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/carousel': typeof AdminCarouselRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/starts': typeof AdminStartsRoute
  '/admin/survey': typeof AdminSurveyRoute
  '/admin/unsubscribes': typeof AdminUnsubscribesRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/clubs/$slug': typeof ClubsSlugRoute
  '/clubs/edit': typeof ClubsEditRoute
  '/event/$id': typeof EventIdRoute
  '/organizers/$slug': typeof OrganizersSlugRoute
  '/organizers/edit': typeof OrganizersEditRoute
  '/payment/fail': typeof PaymentFailRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/starts/$slug': typeof StartsSlugRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/ticket/$id': typeof TicketIdRoute
  '/admin/': typeof AdminIndexRoute
  '/category/': typeof CategoryIndexRoute
  '/clubs/': typeof ClubsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/organizers/': typeof OrganizersIndexRoute
  '/payment-fail/': typeof PaymentFailIndexRoute
  '/payment-success/': typeof PaymentSuccessIndexRoute
  '/starts/': typeof StartsIndexRoute
  '/events/$id/participants': typeof EventsIdParticipantsRoute
  '/events/$id/results': typeof EventsIdResultsRoute
  '/organizer/events/new': typeof OrganizerEventsNewRoute
  '/events/$id/': typeof EventsIdIndexRoute
  '/admin/events/$id/co-organizers': typeof AdminEventsIdCoOrganizersRoute
  '/organizer/events/$id/analytics': typeof OrganizerEventsIdAnalyticsRoute
  '/organizer/events/$id/campaign': typeof OrganizerEventsIdCampaignRoute
  '/organizer/events/$id/changes': typeof OrganizerEventsIdChangesRoute
  '/organizer/events/$id/promo-codes': typeof OrganizerEventsIdPromoCodesRoute
  '/organizer/events/$id/': typeof OrganizerEventsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/contacts'
    | '/features'
    | '/map'
    | '/my-events'
    | '/privacy'
    | '/profile'
    | '/public-offer'
    | '/reset-password'
    | '/survey'
    | '/testimonials'
    | '/unsubscribe'
    | '/user-agreement'
    | '/admin/campaigns'
    | '/admin/carousel'
    | '/admin/seo'
    | '/admin/sessions'
    | '/admin/starts'
    | '/admin/survey'
    | '/admin/unsubscribes'
    | '/category/$category'
    | '/clubs/$slug'
    | '/clubs/edit'
    | '/event/$id'
    | '/organizers/$slug'
    | '/organizers/edit'
    | '/payment/fail'
    | '/payment/success'
    | '/starts/$slug'
    | '/strava/callback'
    | '/ticket/$id'
    | '/admin/'
    | '/category/'
    | '/clubs/'
    | '/organizer/'
    | '/organizers/'
    | '/payment-fail/'
    | '/payment-success/'
    | '/starts/'
    | '/events/$id/participants'
    | '/events/$id/results'
    | '/organizer/events/new'
    | '/events/$id/'
    | '/admin/events/$id/co-organizers'
    | '/organizer/events/$id/analytics'
    | '/organizer/events/$id/campaign'
    | '/organizer/events/$id/changes'
    | '/organizer/events/$id/promo-codes'
    | '/organizer/events/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/contacts'
    | '/features'
    | '/map'
    | '/my-events'
    | '/privacy'
    | '/profile'
    | '/public-offer'
    | '/reset-password'
    | '/survey'
    | '/testimonials'
    | '/unsubscribe'
    | '/user-agreement'
    | '/admin/campaigns'
    | '/admin/carousel'
    | '/admin/seo'
    | '/admin/sessions'
    | '/admin/starts'
    | '/admin/survey'
    | '/admin/unsubscribes'
    | '/category/$category'
    | '/clubs/$slug'
    | '/clubs/edit'
    | '/event/$id'
    | '/organizers/$slug'
    | '/organizers/edit'
    | '/payment/fail'
    | '/payment/success'
    | '/starts/$slug'
    | '/strava/callback'
    | '/ticket/$id'
    | '/admin'
    | '/category'
    | '/clubs'
    | '/organizer'
    | '/organizers'
    | '/payment-fail'
    | '/payment-success'
    | '/starts'
    | '/events/$id/participants'
    | '/events/$id/results'
    | '/organizer/events/new'
    | '/events/$id'
    | '/admin/events/$id/co-organizers'
    | '/organizer/events/$id/analytics'
    | '/organizer/events/$id/campaign'
    | '/organizer/events/$id/changes'
    | '/organizer/events/$id/promo-codes'
    | '/organizer/events/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/contacts'
    | '/features'
    | '/map'
    | '/my-events'
    | '/privacy'
    | '/profile'
    | '/public-offer'
    | '/reset-password'
    | '/survey'
    | '/testimonials'
    | '/unsubscribe'
    | '/user-agreement'
    | '/admin/campaigns'
    | '/admin/carousel'
    | '/admin/seo'
    | '/admin/sessions'
    | '/admin/starts'
    | '/admin/survey'
    | '/admin/unsubscribes'
    | '/category/$category'
    | '/clubs/$slug'
    | '/clubs/edit'
    | '/event/$id'
    | '/organizers/$slug'
    | '/organizers/edit'
    | '/payment/fail'
    | '/payment/success'
    | '/starts/$slug'
    | '/strava/callback'
    | '/ticket/$id'
    | '/admin/'
    | '/category/'
    | '/clubs/'
    | '/organizer/'
    | '/organizers/'
    | '/payment-fail/'
    | '/payment-success/'
    | '/starts/'
    | '/events/$id/participants'
    | '/events/$id/results'
    | '/organizer/events/new'
    | '/events/$id/'
    | '/admin/events/$id/co-organizers'
    | '/organizer/events/$id/analytics'
    | '/organizer/events/$id/campaign'
    | '/organizer/events/$id/changes'
    | '/organizer/events/$id/promo-codes'
    | '/organizer/events/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ContactsRoute: typeof ContactsRoute
  FeaturesRoute: typeof FeaturesRoute
  MapRoute: typeof MapRoute
  MyEventsRoute: typeof MyEventsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  PublicOfferRoute: typeof PublicOfferRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SurveyRoute: typeof SurveyRoute
  TestimonialsRoute: typeof TestimonialsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  UserAgreementRoute: typeof UserAgreementRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminCarouselRoute: typeof AdminCarouselRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminStartsRoute: typeof AdminStartsRoute
  AdminSurveyRoute: typeof AdminSurveyRoute
  AdminUnsubscribesRoute: typeof AdminUnsubscribesRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  ClubsSlugRoute: typeof ClubsSlugRoute
  ClubsEditRoute: typeof ClubsEditRoute
  EventIdRoute: typeof EventIdRoute
  OrganizersSlugRoute: typeof OrganizersSlugRoute
  OrganizersEditRoute: typeof OrganizersEditRoute
  PaymentFailRoute: typeof PaymentFailRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  StartsSlugRoute: typeof StartsSlugRoute
  StravaCallbackRoute: typeof StravaCallbackRoute
  TicketIdRoute: typeof TicketIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  OrganizersIndexRoute: typeof OrganizersIndexRoute
  PaymentFailIndexRoute: typeof PaymentFailIndexRoute
  PaymentSuccessIndexRoute: typeof PaymentSuccessIndexRoute
  StartsIndexRoute: typeof StartsIndexRoute
  EventsIdParticipantsRoute: typeof EventsIdParticipantsRoute
  EventsIdResultsRoute: typeof EventsIdResultsRoute
  OrganizerEventsNewRoute: typeof OrganizerEventsNewRoute
  EventsIdIndexRoute: typeof EventsIdIndexRoute
  AdminEventsIdCoOrganizersRoute: typeof AdminEventsIdCoOrganizersRoute
  OrganizerEventsIdAnalyticsRoute: typeof OrganizerEventsIdAnalyticsRoute
  OrganizerEventsIdCampaignRoute: typeof OrganizerEventsIdCampaignRoute
  OrganizerEventsIdChangesRoute: typeof OrganizerEventsIdChangesRoute
  OrganizerEventsIdPromoCodesRoute: typeof OrganizerEventsIdPromoCodesRoute
  OrganizerEventsIdIndexRoute: typeof OrganizerEventsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-offer': {
      id: '/public-offer'
      path: '/public-offer'
      fullPath: '/public-offer'
      preLoaderRoute: typeof PublicOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-agreement': {
      id: '/user-agreement'
      path: '/user-agreement'
      fullPath: '/user-agreement'
      preLoaderRoute: typeof UserAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/admin/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/carousel': {
      id: '/admin/carousel'
      path: '/admin/carousel'
      fullPath: '/admin/carousel'
      preLoaderRoute: typeof AdminCarouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/starts': {
      id: '/admin/starts'
      path: '/admin/starts'
      fullPath: '/admin/starts'
      preLoaderRoute: typeof AdminStartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/survey': {
      id: '/admin/survey'
      path: '/admin/survey'
      fullPath: '/admin/survey'
      preLoaderRoute: typeof AdminSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unsubscribes': {
      id: '/admin/unsubscribes'
      path: '/admin/unsubscribes'
      fullPath: '/admin/unsubscribes'
      preLoaderRoute: typeof AdminUnsubscribesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/': {
      id: '/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$slug': {
      id: '/clubs/$slug'
      path: '/clubs/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof ClubsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/edit': {
      id: '/clubs/edit'
      path: '/clubs/edit'
      fullPath: '/clubs/edit'
      preLoaderRoute: typeof ClubsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers/': {
      id: '/organizers/'
      path: '/organizers'
      fullPath: '/organizers/'
      preLoaderRoute: typeof OrganizersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers/$slug': {
      id: '/organizers/$slug'
      path: '/organizers/$slug'
      fullPath: '/organizers/$slug'
      preLoaderRoute: typeof OrganizersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers/edit': {
      id: '/organizers/edit'
      path: '/organizers/edit'
      fullPath: '/organizers/edit'
      preLoaderRoute: typeof OrganizersEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-fail/': {
      id: '/payment-fail/'
      path: '/payment-fail'
      fullPath: '/payment-fail/'
      preLoaderRoute: typeof PaymentFailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success/': {
      id: '/payment-success/'
      path: '/payment-success'
      fullPath: '/payment-success/'
      preLoaderRoute: typeof PaymentSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/fail': {
      id: '/payment/fail'
      path: '/payment/fail'
      fullPath: '/payment/fail'
      preLoaderRoute: typeof PaymentFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starts/': {
      id: '/starts/'
      path: '/starts'
      fullPath: '/starts/'
      preLoaderRoute: typeof StartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starts/$slug': {
      id: '/starts/$slug'
      path: '/starts/$slug'
      fullPath: '/starts/$slug'
      preLoaderRoute: typeof StartsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strava/callback': {
      id: '/strava/callback'
      path: '/strava/callback'
      fullPath: '/strava/callback'
      preLoaderRoute: typeof StravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$id': {
      id: '/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof TicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/': {
      id: '/events/$id/'
      path: '/events/$id'
      fullPath: '/events/$id/'
      preLoaderRoute: typeof EventsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/participants': {
      id: '/events/$id/participants'
      path: '/events/$id/participants'
      fullPath: '/events/$id/participants'
      preLoaderRoute: typeof EventsIdParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/results': {
      id: '/events/$id/results'
      path: '/events/$id/results'
      fullPath: '/events/$id/results'
      preLoaderRoute: typeof EventsIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/new': {
      id: '/organizer/events/new'
      path: '/organizer/events/new'
      fullPath: '/organizer/events/new'
      preLoaderRoute: typeof OrganizerEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$id/co-organizers': {
      id: '/admin/events/$id/co-organizers'
      path: '/admin/events/$id/co-organizers'
      fullPath: '/admin/events/$id/co-organizers'
      preLoaderRoute: typeof AdminEventsIdCoOrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$id/': {
      id: '/organizer/events/$id/'
      path: '/organizer/events/$id'
      fullPath: '/organizer/events/$id/'
      preLoaderRoute: typeof OrganizerEventsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$id/analytics': {
      id: '/organizer/events/$id/analytics'
      path: '/organizer/events/$id/analytics'
      fullPath: '/organizer/events/$id/analytics'
      preLoaderRoute: typeof OrganizerEventsIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$id/campaign': {
      id: '/organizer/events/$id/campaign'
      path: '/organizer/events/$id/campaign'
      fullPath: '/organizer/events/$id/campaign'
      preLoaderRoute: typeof OrganizerEventsIdCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$id/changes': {
      id: '/organizer/events/$id/changes'
      path: '/organizer/events/$id/changes'
      fullPath: '/organizer/events/$id/changes'
      preLoaderRoute: typeof OrganizerEventsIdChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/$id/promo-codes': {
      id: '/organizer/events/$id/promo-codes'
      path: '/organizer/events/$id/promo-codes'
      fullPath: '/organizer/events/$id/promo-codes'
      preLoaderRoute: typeof OrganizerEventsIdPromoCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ContactsRoute: ContactsRoute,
  FeaturesRoute: FeaturesRoute,
  MapRoute: MapRoute,
  MyEventsRoute: MyEventsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  PublicOfferRoute: PublicOfferRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SurveyRoute: SurveyRoute,
  TestimonialsRoute: TestimonialsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  UserAgreementRoute: UserAgreementRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminCarouselRoute: AdminCarouselRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminStartsRoute: AdminStartsRoute,
  AdminSurveyRoute: AdminSurveyRoute,
  AdminUnsubscribesRoute: AdminUnsubscribesRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  ClubsSlugRoute: ClubsSlugRoute,
  ClubsEditRoute: ClubsEditRoute,
  EventIdRoute: EventIdRoute,
  OrganizersSlugRoute: OrganizersSlugRoute,
  OrganizersEditRoute: OrganizersEditRoute,
  PaymentFailRoute: PaymentFailRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  StartsSlugRoute: StartsSlugRoute,
  StravaCallbackRoute: StravaCallbackRoute,
  TicketIdRoute: TicketIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  ClubsIndexRoute: ClubsIndexRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
  OrganizersIndexRoute: OrganizersIndexRoute,
  PaymentFailIndexRoute: PaymentFailIndexRoute,
  PaymentSuccessIndexRoute: PaymentSuccessIndexRoute,
  StartsIndexRoute: StartsIndexRoute,
  EventsIdParticipantsRoute: EventsIdParticipantsRoute,
  EventsIdResultsRoute: EventsIdResultsRoute,
  OrganizerEventsNewRoute: OrganizerEventsNewRoute,
  EventsIdIndexRoute: EventsIdIndexRoute,
  AdminEventsIdCoOrganizersRoute: AdminEventsIdCoOrganizersRoute,
  OrganizerEventsIdAnalyticsRoute: OrganizerEventsIdAnalyticsRoute,
  OrganizerEventsIdCampaignRoute: OrganizerEventsIdCampaignRoute,
  OrganizerEventsIdChangesRoute: OrganizerEventsIdChangesRoute,
  OrganizerEventsIdPromoCodesRoute: OrganizerEventsIdPromoCodesRoute,
  OrganizerEventsIdIndexRoute: OrganizerEventsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
